config/routes.rb
Rails.application.routes.draw do

  resources :multyproms
  resources :beneficiados
  resources :riesgos
  resources :familiars
    post '/tamizajes' => "apptamizajes#create2", :controller => "apptamizajes"
    post  '/tamizajes/escuela/:id' => "tamizajes#show_tamizaje", as: "show_tamizaje"
    post  '/tamizajes/escuela/grupos/:id' => "tamizajes#show_grupos", as: "show_grupos"
    post  '/tamizajes/escuela/termino_tam/:id' => "tamizajes#termino_tam", as: "termino_tam"
    get  '/tamizajes/escuela/grupos/riesgo/:id' => "tamizajes#show_riesgo", as: "show_riesgo"

  resources :parentescos
  resources :etnia
  resources :civils
    get     "/prueba/:id" => "tamizajes#prueba", as: "prueba"
    post    "/tamizajes/.:id" => "tamizajes#index", as: "escuelas_new_flag"
    get    "/tamizajes/" => "tamizajes#index", as: "escuelas"
    post   "/tamizajes/escuela/tam/new/create" => "tamizajes#create", :controller =>"tamizajes", as: "tam_create"
    post    "/tamizajes/escuela/tam/new"  => "tamizajes#new", as: "new_tamizaje"
    get    "/tamizajes/escuela/:id/edit" => "tamizajes#edit", as: "edit_tamizaje"
    get    "/tamizajes/:id" => "tamizajes#show", as: "tamizaje"
    patch  "/tamizajes/escuela/:id" => "tamizajes#update"
    put    "/tamizajes/escuela/:id" => "tamizajes#update"
    delete "/tamizajes/escuela/:id" => "tamizajes#destroy"

    resources :estatuses
  resources :patients #do
  get '/patients/datos/:id', to: 'patients#datos', as: 'datos'
  get '/meetings/actualizar/:id', to: 'meetings#actualizar', as: 'actualiza'
  resources :imca
  resources :usuarios
  resources :tamizajes_tots
  resources :tratamientos_bcs
  resources :personal_cts
  resources :personas_vgs
  resources :consultas_subs
  resources :consultas_pvs
  resources :capacitaciones_recs
  resources :capacitaciones_ots
  resources :adolescentes_its
  resources :adolescentes_aps
  resources :indicadores
  resources :meta
  resources :psychologists
  resources :expedientes
  resources :sustancia
  resources :programas
  resources :states
  resources :municipios
  resources :meetings
  resources :reportes
  resources :siceca
  resources :indicadoresxedad
  resources :reporte_pacientes
    
  devise_for :users

  resources :user
  get "welcome/index"
  get "meetings/new"

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root "welcome#unregistered", as: :unregistered_root
    end
  end

end

app/models/personal_ct.rb
class PersonalCt < ActiveRecord::Base
	belongs_to :psychologist
	before_save :default_values
	before_save :suma

    validates :psychologist_id, :fecha, :presence=> true

	def default_values
		self.h ||=0
		self.h1 ||=0
		self.h2 ||=0
		self.h3 ||=0
		self.h4 ||=0
		self.h5 ||=0
		self.h6 ||=0
		self.h7 ||=0
		self.h8 ||=0
		self.h9 ||=0
		self.h10 ||=0
		self.m ||=0
		self.m1 ||=0
		self.m2 ||=0
		self.m3 ||=0
		self.m4 ||=0
		self.m5 ||=0
		self.m6 ||=0
		self.m7 ||=0
		self.m8 ||=0
		self.m9 ||=0
		self.m10 ||=0
		#self.psychologist_id ||= current_user.psychologist_id

	end

	def suma
		self.h= self.h1+self.h2+self.h3+self.h4+self.h5+self.h6+self.h7+self.h8+self.h9+self.h10 
		self.m=	self.m1+self.m2+self.m3+self.m4+self.m5+self.m6+self.m7+self.m8+self.m9+self.m10
	end
end

app/controllers/personal_cts_controller.rb
class PersonalCtsController < ApplicationController
  before_action :set_personal_ct, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /personal_cts
  # GET /personal_cts.json
  def index
    @personal_cts = PersonalCt.all
  end

  # GET /personal_cts/1
  # GET /personal_cts/1.json
  def show
  end

  # GET /personal_cts/new
  def new
    @personal_ct = PersonalCt.new
  end

  # GET /personal_cts/1/edit
  def edit
  end

  # POST /personal_cts
  # POST /personal_cts.json
  def create
    @personal_ct = PersonalCt.new(personal_ct_params)

    respond_to do |format|
      if @personal_ct.save
        format.html { redirect_to @personal_ct, notice: 'Personal ct was successfully created.' }
        format.json { render :show, status: :created, location: @personal_ct }
      else
        format.html { render :new }
        format.json { render json: @personal_ct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_cts/1
  # PATCH/PUT /personal_cts/1.json
  def update
    respond_to do |format|
      if @personal_ct.update(personal_ct_params)
        format.html { redirect_to @personal_ct, notice: 'Personal ct was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal_ct }
      else
        format.html { render :edit }
        format.json { render json: @personal_ct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_cts/1
  # DELETE /personal_cts/1.json
  def destroy
    @personal_ct.destroy
    respond_to do |format|
      format.html { redirect_to personal_cts_url, notice: 'Personal ct was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_ct
      @personal_ct = PersonalCt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_ct_params
      params.require(:personal_ct).permit(:h, :m, :fecha, :psychologist_id, :h1, :h2, :h3, :h4, :h5, :h6, :h7, :h8, :h9, :h10, :m1, :m2, :m3, :m4, :m5, :m6, :m7, :m8, :m9 ,:m10)
    end
end

app/helpers/personal_cts_helper.rb
module PersonalCtsHelper
end

app/views/personal_cts/_form.html.erb
<div class="board col-md-6">
  <%= form_for(@personal_ct) do |f| %>
  <% if @personal_ct.errors.any? %>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
      <% @personal_ct.errors.full_messages.each do |message| %>
        <%= message%><br>
      <% end %>
  </div>
  <% end %>

 
  <!--<div class="form-group label-floating">
    <%#= f.label :h, "hombres" %><br>
    <%#= f.text_field :h ,class: "form-control text-center"%>
  </div>

  <div class="form-group label-floating">
    <%#= f.label :m, "mujeres" %><br>
    <%#= f.text_field :m ,class: "form-control text-center"%>
  </div>-->

  <div class="form-group label-floating">
    <%= f.label :fecha, "fecha" %><br>
    <%= f.date_select :fecha,class: "form-control text-center"%>
  </div>

  <div class="form-group label-floating">
    <%= f.label :psychologist_id, "psicologo" %><br>
    <%= f.select(:psychologist_id, Psychologist.all.collect {|ps| [ps.nombre+" "+ps.apellidoP+" "+ps.apellidoM, ps.id]}, :prompt => 'Selecciona uno')%>
  </div>
  
    <div class="form-group label-floating">
    <%=f.label "Edades 5 a 9"%> <br>
    <%= f.label :h1,"Hombres" %> <%= f.label :m1,"Mujeres" %><br>
    <%= f.number_field :h1 %><%= f.number_field :m1 %> <br>
  </div>
  <div class="form-group label-floating">
    <%=f.label "Edades 10 a 11"%> <br>
    <%= f.label :h2,"Hombres" %>  <%= f.label :m2,"Mujeres" %><br>
    <%= f.number_field :h2 %><%= f.number_field :m2 %> <br>        
  </div>
  <div class="form-group label-floating">
    <%=f.label "Edades 12 a 14"%> <br>
    <%= f.label :h3,"Hombres" %> <%= f.label :m3,"Mujeres" %><br>
    <%= f.number_field :h3 %>  <%= f.number_field :m3 %> <br>         
  </div>
   
  <div class="form-group label-floating">
    <%=f.label "Edades 15 a 17"%> <br>
    <%= f.label :h4,"Hombres" %> <%= f.label :m4,"Mujeres" %><br>
    <%= f.number_field :h4 %>  <%= f.number_field :m4 %> <br>      
  </div>

  <div class="form-group label-floating">
    <%=f.label "Edades 18 a 19"%> <br>
    <%= f.label :h5,"Hombres" %> <%= f.label :m5,"Mujeres" %><br>
    <%= f.number_field :h5 %> <%= f.number_field :m5 %>  <br>     
  </div>
  <div class="form-group label-floating">
    <%=f.label "Edades 20 a 29"%> <br>
    <%= f.label :h6,"Hombres" %> <%= f.label :m6,"Mujeres" %><br>
    <%= f.number_field :h6 %>  <%= f.number_field :m6 %> <br>
  </div>
  <div class="form-group label-floating">
    <%=f.label "Edades 30 a 34"%> <br>
    <%= f.label :h7,"Hombres" %> <%= f.label :m7,"Mujeres" %><br>
    <%= f.number_field :h7 %> <%= f.number_field :m7 %> <br>
  </div>
  <div class="form-group label-floating">
    <%=f.label "edades 35 a 49"%> <br>
    <%= f.label :h8,"Hombres" %> <%= f.label :m8,"Mujeres" %><br>
    <%= f.number_field :h8 %> <%= f.number_field :m8 %><br>  
  </div>
  <div class="form-group label-floating">
    <%= f.label "edades 50 a 59"%> <br>
    <%= f.label :h9,"Hombres" %>  <%= f.label :m9,"Mujeres" %><br>
    <%= f.number_field :h9 %> <%= f.number_field :m9 %><br>
  </div>
  <div class="form-group label-floating">
    <%= f.label "edades 60 y mas" %> <br>
    <%= f.label :h10,"Hombres" %> <%= f.label :m10,"Mujeres" %><br>
    <%= f.number_field :h10 %> <%= f.number_field :m10 %><br>
  </div>

 

  <div class="actions">
    <%= f.submit "Agregar", class: "btn btn-raised btn-success" %>
  </div>
<% end %>

</div>

app/views/personal_cts/_personal_ct.html.erb
<div class="list-group-item">
  <div class="row-action-primary">
    <%= link_to personal_ct do %>
      <i class="fa fa-heartbeat" aria-hidden="true"></i>
    <% end %>
  </div>
  <div class="row-content">
    <div class="action-secondary">
      <%= link_to edit_personal_ct_path(@personal_ct) do %>
        <i class="fa fa-pencil-square-o"></i>
      <% end %>
    </div>
    <h4 class="list-group-item-heading"><%= personal_ct.id_personal_ct %> </h4>
    <p class="list-group-item-text"><h5>Fecha de Creacion</h5></p>
    <p class="list-group-item-text"><%= personal_ct.created_at %></p>
  </div>
</div>
<div class="list-group-separator"></div>

app/views/personal_cts/edit.html.erb
<div class="row board ">
	<div class="col-md-12">
		<div class="panel panel-success">
		  <div class="panel-heading">
		    <h2 class="panel-title"><i class="fa fa-stethoscope"></i> Editar Personal Capacitado en Cesacion del Tabaco</h2>
		  </div>
		  <div class="panel-body text-center"><h1>Datos de Personal Capacitado en Cesacion del Tabaco</h1>

        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/personal_cts/index.html.erb
<% if notice %>
  <div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= notice %>
  </div>
<% end%>
<div class="row board ">
  <div class="col-md-5">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-search"></i> Buscar Personal Capacitado en Cesacion del Tabaco</h3>
      </div>
      <div class="panel-body text-center">
        <%= form_tag personal_ct_path, method: :get do %>
          <div class="form-group label-floating">
            <%= text_field_tag :id_personal_ct, params[:id_personal_ct] , :class=>"form-control text-center" , placeholder: "ID Personal Capacitado en Cesacion del Tabaco" %>
          </div>
          <div class="actions">
          <%= submit_tag "Buscar", name: nil, class: "btn btn-raised btn-info" %>
          </div>
        <% end %>
        <div class="panel panel-default">
          <div class="list-group">
              <%= render @personal_cts %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-7">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h1 class="panel-title"><i class="fa fa-stethoscope"></i> Personal Capacitado en Cesacion del Tabaco</h1>
      </div>
      <div class="panel-body text-center">
        <div class="list-group">
          <%= render @personal_cts %>
        </div>
        <%= link_to 'Agregar Personal CT', new_personal_ct_path, class: "btn btn-raised btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/personal_cts/new.html.erb
<div class="row board ">
	<div class="col-md-12">
		<div class="panel panel-success">
		  <div class="panel-heading">
		    <h2 class="panel-title"><i class="fa fa-stethoscope"></i> Personal Capacitado en Cesacion del Tabaco</h2>
		  </div>
		  <div class="panel-body text-center"><h1>Datos Personal Capacitado en Cesacion del Tabaco</h1>

        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/personal_cts/show.html.erb
<div class="row board ">
	<div class="col-md-7">
		<div class="panel panel-success">
		  <div class="panel-heading">
		    <h1 class="panel-title"><i class="fa fa-folder-o"></i> Personal Capacitado en Cesacion del Tabaco <strong>ID <%= @personal_ct.id.to_s %></strong></h1>
		  </div>
		  <div class="panel-body text-center">
        <div class="list-group">
          <div class="list-group-item">
            <div class="row-action-primary">
                <i class="fa fa-heartbeat"></i>
            </div>
            <div class="row-content">
              <div class="action-secondary">
                <%= link_to edit_personal_ct_path(@personal_ct) do %>
                  <i class="fa fa-pencil-square-o"></i>
                <% end %>
              </div>
              <h3 class="list-group-item-heading"><strong>Personal Capacitado en Cesacion del Tabaco: <%= @personal_ct.id.to_s %></strong></h3>
							<p class="list-group-item-text"><strong>Hombres: </strong><%= @personal_ct.h.to_s%></p>
							<p class="list-group-item-text"><strong>Mujeres: </strong><%= @personal_ct.m.to_s%></p>
							<p class="list-group-item-text"><strong>Total: </strong><%= (@personal_ct.h+@personal_ct.m).to_s%></p>
							<p class="list-group-item-text"><strong>Fecha: </strong><%= @personal_ct.fecha%><br></p>
							<p class="list-group-item-text"><strong>Psicologo: </strong><%= @personal_ct.psychologist_id.to_s%><br></p>
              <p class="list-group-item-text"><strong>Hombres 5 a 9: </strong><%= @personal_ct.h1.to_s%><br></p>
              <p class="list-group-item-text"><strong>Mujeres 5 a 9: </strong><%= @personal_ct.m1.to_s%><br></p>
              <p class="list-group-item-text"><strong>Hombres 10 a 11: </strong><%= @personal_ct.h2.to_s%><br></p>
              <p class="list-group-item-text"><strong>Mujeres 10 a 11: </strong><%= @personal_ct.m2.to_s%><br></p>
              <p class="list-group-item-text"><strong>Hombres 12 a 14: </strong><%= @personal_ct.h3%><br></p>
              <p class="list-group-item-text"><strong>Mujeres 12 a 14: </strong><%= @personal_ct.m3.to_s%><br></p>
              <p class="list-group-item-text"><strong>Hombres 15 a 17: </strong><%= @personal_ct.h4.to_s%><br></p>
              <p class="list-group-item-text"><strong>Mujeres 15 a 17: </strong><%= @personal_ct.m4.to_s%><br></p>
              <p class="list-group-item-text"><strong>Hombres 18 a 19: </strong><%= @personal_ct.h5.to_s%><br></p>
              <p class="list-group-item-text"><strong>Mujeres 18 a 19: </strong><%= @personal_ct.m5.to_s%><br></p>
              <p class="list-group-item-text"><strong>Hombres 20 a 29: </strong><%= @personal_ct.h6.to_s%><br></p>
              <p class="list-group-item-text"><strong>Mujeres 20 a 29: </strong><%= @personal_ct.m6.to_s%><br></p>
              <p class="list-group-item-text"><strong>Hombres 30 a 34: </strong><%= @personal_ct.h7.to_s%><br></p>
              <p class="list-group-item-text"><strong>Mujeres 30 a 34: </strong><%= @personal_ct.m7.to_s%><br></p>
              <p class="list-group-item-text"><strong>Hombres 35 a 39: </strong><%= @personal_ct.h8.to_s%><br></p>
              <p class="list-group-item-text"><strong>Mujeres 35 a 39: </strong><%= @personal_ct.m8.to_s%><br></p>
              <p class="list-group-item-text"><strong>Hombres 40 a 59: </strong><%= @personal_ct.h9.to_s%><br></p>
              <p class="list-group-item-text"><strong>Mujeres 40 a 59: </strong><%= @personal_ct.m9.to_s%><br></p>
              <p class="list-group-item-text"><strong>Hombres 60 y mas: </strong><%= @personal_ct.h10.to_s%><br></p>
              <p class="list-group-item-text"><strong>Mujeres 60 y mas: </strong><%= @personal_ct.m10.to_s%><br></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-5">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-calendar-check-o" aria-hidden="true""></i> Personal Capacitado en Cesacion del Tabaco</h3>
      </div>
      <div class="panel-body">
        <div class="panel-body text-center">
          <%= link_to 'Indicadores Generales', indicadores_path, class: "btn btn-raised btn-primary"%><br>
          <br>
          <%= link_to 'Indicadores por rango de edad', indicadoresxedad_index_path, class: "btn btn-raised btn-primary"%><br>
        </div>  
      </div>
    </div>
  </div>
</div>