config/routes.rb
Rails.application.routes.draw do

  resources :multyproms
  resources :beneficiados
  resources :riesgos
  resources :familiars
    post '/tamizajes' => "apptamizajes#create2", :controller => "apptamizajes"
    post  '/tamizajes/escuela/:id' => "tamizajes#show_tamizaje", as: "show_tamizaje"
    post  '/tamizajes/escuela/grupos/:id' => "tamizajes#show_grupos", as: "show_grupos"
    post  '/tamizajes/escuela/termino_tam/:id' => "tamizajes#termino_tam", as: "termino_tam"
    get  '/tamizajes/escuela/grupos/riesgo/:id' => "tamizajes#show_riesgo", as: "show_riesgo"

  resources :parentescos
  resources :etnia
  resources :civils
    get     "/prueba/:id" => "tamizajes#prueba", as: "prueba"
    post    "/tamizajes/.:id" => "tamizajes#index", as: "escuelas_new_flag"
    get    "/tamizajes/" => "tamizajes#index", as: "escuelas"
    post   "/tamizajes/escuela/tam/new/create" => "tamizajes#create", :controller =>"tamizajes", as: "tam_create"
    post    "/tamizajes/escuela/tam/new"  => "tamizajes#new", as: "new_tamizaje"
    get    "/tamizajes/escuela/:id/edit" => "tamizajes#edit", as: "edit_tamizaje"
    get    "/tamizajes/:id" => "tamizajes#show", as: "tamizaje"
    patch  "/tamizajes/escuela/:id" => "tamizajes#update"
    put    "/tamizajes/escuela/:id" => "tamizajes#update"
    delete "/tamizajes/escuela/:id" => "tamizajes#destroy"

    resources :estatuses
  resources :patients #do
  get '/patients/datos/:id', to: 'patients#datos', as: 'datos'
  get '/meetings/actualizar/:id', to: 'meetings#actualizar', as: 'actualiza'
  resources :imca
  resources :usuarios
  resources :tamizajes_tots
  resources :tratamientos_bcs
  resources :personal_cts
  resources :personas_vgs
  resources :consultas_subs
  resources :consultas_pvs
  resources :capacitaciones_recs
  resources :capacitaciones_ots
  resources :adolescentes_its
  resources :adolescentes_aps
  resources :indicadores
  resources :meta
  resources :psychologists
  resources :expedientes
  resources :sustancia
  resources :programas
  resources :states
  resources :municipios
  resources :meetings
  resources :reportes
  resources :siceca
  resources :indicadoresxedad
  resources :reporte_pacientes
    
  devise_for :users

  resources :user
  get "welcome/index"
  get "meetings/new"

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root "welcome#unregistered", as: :unregistered_root
    end
  end

end

app/models/civil.rb
class Civil < ActiveRecord::Base
  has_many :patients
  before_save :upcase

  def upcase
    self.civil.upcase!
  end
end

app/controllers/civils_controller.rb
class CivilsController < ApplicationController
  before_action :set_civil, only: [:show, :edit, :update, :destroy]

  # GET /civils
  # GET /civils.json
  def index
    @civils = Civil.all
  end

  # GET /civils/1
  # GET /civils/1.json
  def show
  end

  # GET /civils/new
  def new
    @civil = Civil.new
  end

  # GET /civils/1/edit
  def edit
  end

  # POST /civils
  # POST /civils.json
  def create
    @civil = Civil.new(civil_params)

    respond_to do |format|
      if @civil.save
        format.html { redirect_to @civil, notice: 'Civil was successfully created.' }
        format.json { render :show, status: :created, location: @civil }
      else
        format.html { render :new }
        format.json { render json: @civil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /civils/1
  # PATCH/PUT /civils/1.json
  def update
    respond_to do |format|
      if @civil.update(civil_params)
        format.html { redirect_to @civil, notice: 'Civil was successfully updated.' }
        format.json { render :show, status: :ok, location: @civil }
      else
        format.html { render :edit }
        format.json { render json: @civil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /civils/1
  # DELETE /civils/1.json
  def destroy
    @civil.destroy
    respond_to do |format|
      format.html { redirect_to civils_url, notice: 'Civil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_civil
      @civil = Civil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def civil_params
      params.require(:civil).permit(:civil)
    end
end

app/helpers/civils_helper.rb
module CivilsHelper
end

app/views/civils/_form.html.erb
<%= form_for(@civil) do |f| %>
  <% if @civil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@civil.errors.count, "error") %> prohibited this civil from being saved:</h2>

      <ul>
      <% @civil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :civil %><br>
    <%= f.text_field :civil %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/civils/edit.html.erb
<h1>Editing Civil</h1>

<%= render 'form' %>

<%= link_to 'Show', @civil %> |
<%= link_to 'Back', civils_path %>

app/views/civils/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Civils</h1>

<table>
  <thead>
    <tr>
      <th>Civil</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @civils.each do |civil| %>
      <tr>
        <td><%= civil.civil %></td>
        <td><%= link_to 'Show', civil %></td>
        <td><%= link_to 'Edit', edit_civil_path(civil) %></td>
        <td><%= link_to 'Destroy', civil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Civil', new_civil_path %>

app/views/civils/new.html.erb
<h1>New Civil</h1>

<%= render 'form' %>

<%= link_to 'Back', civils_path %>

app/views/civils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Civil:</strong>
  <%= @civil.civil %>
</p>

<%= link_to 'Edit', edit_civil_path(@civil) %> |
<%= link_to 'Back', civils_path %>