config/routes.rb
Rails.application.routes.draw do

  resources :multyproms
  resources :beneficiados
  resources :riesgos
  resources :familiars
    post '/tamizajes' => "apptamizajes#create2", :controller => "apptamizajes"
    post  '/tamizajes/escuela/:id' => "tamizajes#show_tamizaje", as: "show_tamizaje"
    post  '/tamizajes/escuela/grupos/:id' => "tamizajes#show_grupos", as: "show_grupos"
    post  '/tamizajes/escuela/termino_tam/:id' => "tamizajes#termino_tam", as: "termino_tam"
    get  '/tamizajes/escuela/grupos/riesgo/:id' => "tamizajes#show_riesgo", as: "show_riesgo"

  resources :parentescos
  resources :etnia
  resources :civils
    get     "/prueba/:id" => "tamizajes#prueba", as: "prueba"
    post    "/tamizajes/.:id" => "tamizajes#index", as: "escuelas_new_flag"
    get    "/tamizajes/" => "tamizajes#index", as: "escuelas"
    post   "/tamizajes/escuela/tam/new/create" => "tamizajes#create", :controller =>"tamizajes", as: "tam_create"
    post    "/tamizajes/escuela/tam/new"  => "tamizajes#new", as: "new_tamizaje"
    get    "/tamizajes/escuela/:id/edit" => "tamizajes#edit", as: "edit_tamizaje"
    get    "/tamizajes/:id" => "tamizajes#show", as: "tamizaje"
    patch  "/tamizajes/escuela/:id" => "tamizajes#update"
    put    "/tamizajes/escuela/:id" => "tamizajes#update"
    delete "/tamizajes/escuela/:id" => "tamizajes#destroy"

    resources :estatuses
  resources :patients #do
  get '/patients/datos/:id', to: 'patients#datos', as: 'datos'
  get '/meetings/actualizar/:id', to: 'meetings#actualizar', as: 'actualiza'
  resources :imca
  resources :usuarios
  resources :tamizajes_tots
  resources :tratamientos_bcs
  resources :personal_cts
  resources :personas_vgs
  resources :consultas_subs
  resources :consultas_pvs
  resources :capacitaciones_recs
  resources :capacitaciones_ots
  resources :adolescentes_its
  resources :adolescentes_aps
  resources :indicadores
  resources :meta
  resources :psychologists
  resources :expedientes
  resources :sustancia
  resources :programas
  resources :states
  resources :municipios
  resources :meetings
  resources :reportes
  resources :siceca
  resources :indicadoresxedad
  resources :reporte_pacientes
    
  devise_for :users

  resources :user
  get "welcome/index"
  get "meetings/new"

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root "welcome#unregistered", as: :unregistered_root
    end
  end

end

app/models/adolescentes_it.rb
class AdolescentesIt < ActiveRecord::Base
	belongs_to :psychologist
	before_save :default_values
	before_save :suma

    validates :psychologist_id, :fecha, :presence=> true

	def default_values
		self.h ||=0
		self.h3 ||=0
		self.h4 ||=0
		self.m ||=0
		self.m3 ||=0
		self.m4 ||=0
	end

	def suma
		self.h=self.h3+self.h4
		self.m=self.m3+self.m4
	end

	def self.query(psy, id)
        tmp=psy
        tmp1=id
        tmp2=" "
        tmp3=" "
        if tmp1.eql?(1)
            date = Date.today
            año= date.strftime"%Y".to_s
            mes= date.strftime"%m".to_s
            tmp2=año+"-"+mes+"-"+"01"
            tmp3=año+"-"+mes+"-"+"19"
        elsif tmp1.eql?(2)
            date = Date.today
            año= date.strftime"%Y".to_s
            mes=(((date.strftime"%m").to_i)-1).to_s
            tmp2=año+"-"+mes+"-"+"20"
            tmp3=año+"-"+mes+"-"+"31"
        end 
        
		##Patient.where("sexo =? AND edad >=? AND edad<=?","Femenino",20,29 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,4,"2016-03-01","2016-06-31").includes(:patient_counts).where("aasm_state = ?", "primera").count
    #qf1= Patient.where("sexo =? AND edad >=? AND edad<=?","Femenino",12,14 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,tmp,fechaIni,fechaFin).includes(:patient_counts).where("aasm_state = ?", "primera").count
    qf1= PatientCount.where("psychologist_id=? AND fecha BETWEEN ? AND ? AND aasm_status=?",tmp,tmp2,tmp3, "primera").joins(:patient).where("sexo =? AND edad >=? AND edad<=?","Femenino",12,14).count
    #qf2= Patient.where("sexo =? AND edad >=? AND edad<=?","Femenino",15,17 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,tmp,fechaIni,fechaFin).includes(:patient_counts).where("aasm_state = ?", "primera").count
    qf2= PatientCount.where("psychologist_id=? AND fecha BETWEEN ? AND ? AND aasm_status=?",tmp,tmp2,tmp3, "primera").joins(:patient).where("sexo =? AND edad >=? AND edad<=?","Femenino",15,17).count
    	
    ##queryf3= Patient.where("sexo =? AND edad >=? AND edad<=?","Femenino",12,14 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "subsecuente").count
    ##queryf4= Patient.where("sexo =? AND edad >=? AND edad<=?","Femenino",15,17 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "subsecuente").count
    ##queryf5= Patient.where("sexo =? AND edad >=? AND edad<=?","Femenino",12,14 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "recaida").count
    ##queryf6= Patient.where("sexo =? AND edad >=? AND edad<=?","Femenino",15,17 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "recaida").count
    ##queryf7= Patient.where("sexo =? AND edad >=? AND edad<=?","Femenino",12,14 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "segimiento").count
    ##queryf8= Patient.where("sexo =? AND edad >=? AND edad<=?","Femenino",15,17 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "segimiento").count
    ##queryf9= Patient.where("sexo =? AND edad >=? AND edad<=?","Femenino",12,14 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "alta").count
    ##queryf10= Patient.where("sexo =? AND edad >=? AND edad<=?","Femenino",15,17 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "alta").count
    tf=qf1+qf2

		#qm1= Patient.where("sexo =? AND edad >=? AND edad<=?","Masculino",12,14 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,tmp,fechaIni,fechaFin).includes(:patient_counts).where("aasm_state = ?", "primera").count
    qm1= PatientCount.where("psychologist_id=? AND fecha BETWEEN ? AND ? AND aasm_status=?",tmp,tmp2,tmp3, "primera").joins(:patient).where("sexo =? AND edad >=? AND edad<=?","Masculino",12,14).count     
    #qm2= Patient.where("sexo =? AND edad >=? AND edad<=?","Masculino",15,17 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,tmp,fechaIni,fechaFin).includes(:patient_counts).where("aasm_state = ?", "primera").count
    qm2= PatientCount.where("psychologist_id=? AND fecha BETWEEN ? AND ? AND aasm_status=?",tmp,tmp2,tmp3, "primera").joins(:patient).where("sexo =? AND edad >=? AND edad<=?","Masculino",15,17).count     
    ##querym3= Patient.where("sexo =? AND edad >=? AND edad<=?","Masculino",12,14 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "subsecuente").count
    ##querym4= Patient.where("sexo =? AND edad >=? AND edad<=?","Masculino",15,17 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "subsecuente").count
    ##querym5= Patient.where("sexo =? AND edad >=? AND edad<=?","Masculino",12,14 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "recaida").count
    ##querym6= Patient.where("sexo =? AND edad >=? AND edad<=?","Masculino",15,17 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "recaida").count
    ##querym7= Patient.where("sexo =? AND edad >=? AND edad<=?","Masculino",12,14 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "segimiento").count
    ##querym8= Patient.where("sexo =? AND edad >=? AND edad<=?","Masculino",15,17 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "segimiento").count
    ##querym9= Patient.where("sexo =? AND edad >=? AND edad<=?","Masculino",12,14 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "alta").count
    ##querym10= Patient.where("sexo =? AND edad >=? AND edad<=?","Masculino",15,17 ).joins(:meetings).where("termino = ? AND psychologist_id=? AND start_time BETWEEN ? AND ? ",2,params[:id],date.strftime "%Y-%m-01",date.strftime "%Y-%m-31").includes(:patient_counts).where("aasm_state = ?", "alta").count
    tm=qm1+qm2
    ##Meeting.joins(:patient).where(:psychologist_id=>params[tmp], :fecha=>(params[:date_start]..params[:date_end]),(date.strftime "%Y-%m-01"),(date.strftime "%Y-%m-31")).includes(patient_counts)
    AdolescentesIt.create(h:tm, m:tf, fecha:tmp3, psychologist_id:tmp, h3:qm1, h4:qm2, m3:qf1, m4:qf2)
	end

end

app/controllers/adolescentes_its_controller.rb
class AdolescentesItsController < ApplicationController
  before_action :set_adolescentes_it, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /adolescentes_its
  # GET /adolescentes_its.json
  def index
    @adolescentes_its = AdolescentesIt.all
    @adolit= Meeting.where(:start_time => (params[:date_start]..params[:date_end]), :termino => '2').select(:patient_id)
    #Patient.where(:edad).count

    @adolit2= @adolit.map { |e| e[:patient_id]}
    
    #@num=@m.count
    @edades= []
    @adolit2.each do |e|
      adit= Patient.select(:edad).where(:id => e, :sexo =>'Masculino')
      adol=adit.map {|m| m[:edad]} 
      @edades.push m 
    end

    @edades.each do |e|
      @h= AdolescentesIt
      @m= AdolescentesIt
    end
  end

  # GET /adolescentes_its/1
  # GET /adolescentes_its/1.json
  def show
  end

  # GET /adolescentes_its/new
  def new
    @adolescentes_it = AdolescentesIt.new
  end

  # GET /adolescentes_its/1/edit
  def edit
  end

  # POST /adolescentes_its
  # POST /adolescentes_its.json
  def create
    @adolescentes_it = AdolescentesIt.new(adolescentes_it_params)

    respond_to do |format|
      if @adolescentes_it.save
        format.html { redirect_to @adolescentes_it, notice: 'Adolescentes it was successfully created.' }
        format.json { render :show, status: :created, location: @adolescentes_it }
      else
        format.html { render :new }
        format.json { render json: @adolescentes_it.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adolescentes_its/1
  # PATCH/PUT /adolescentes_its/1.json
  def update
    respond_to do |format|
      if @adolescentes_it.update(adolescentes_it_params)
        format.html { redirect_to @adolescentes_it, notice: 'Adolescentes it was successfully updated.' }
        format.json { render :show, status: :ok, location: @adolescentes_it }
      else
        format.html { render :edit }
        format.json { render json: @adolescentes_it.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adolescentes_its/1
  # DELETE /adolescentes_its/1.json
  def destroy
    @adolescentes_it.destroy
    respond_to do |format|
      format.html { redirect_to adolescentes_its_url, notice: 'Adolescentes it was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adolescentes_it
      @adolescentes_it = AdolescentesIt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adolescentes_it_params
      params.require(:adolescentes_it).permit(:h, :m, :fecha, :psychologist_id, :h3, :h4, :m3, :m4)
    end
end

app/helpers/adolescentes_its_helper.rb
module AdolescentesItsHelper
end

app/views/adolescentes_its/_adolescentes_it.html.erb
<div class="list-group-item">
  <div class="row-action-primary">
    <%= link_to adolescentes_it do %>
      <i class="fa fa-heartbeat" aria-hidden="true"></i>
    <% end %>
  </div>
  <div class="row-content">
    <div class="action-secondary">
      <%= link_to edit_adolescentes_it_path(@adolescentes_it) do %>
        <i class="fa fa-pencil-square-o"></i>
      <% end %>
    </div>
    <h4 class="list-group-item-heading"><%= adolescentes_it.id_adolescentes_it %> </h4>
    <p class="list-group-item-text"><h5>Fecha de Creacion</h5></p>
    <p class="list-group-item-text"><%= adolescentes_it.created_at %></p>
  </div>
</div>
<div class="list-group-separator"></div>

app/views/adolescentes_its/_form.html.erb
<div class="board col-md-6">
  <%= form_for(@adolescentes_it) do |f| %>
  <% if @adolescentes_it.errors.any? %>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
      <% @adolescentes_it.errors.full_messages.each do |message| %>
        <%= message%><br>
      <% end %>
  </div>
  <% end %>

 
  <!--<div class="form-group label-floating">
    <%#= f.label :h, "hombres" %><br>
    <%#= f.text_field :h ,class: "form-control text-center"%>
  </div>

  <div class="form-group label-floating">
    <%#= f.label :m, "mujeres" %><br>
    <%#= f.text_field :m ,class: "form-control text-center"%>
  </div>-->

  <div class="form-group label-floating">
    <%= f.label :fecha, "fecha" %><br>
    <%= f.date_select :fecha,class: "form-control text-center"%>
  </div>

  <div class="form-group label-floating">
    <%= f.label :psychologist_id %><br>
    <%= f.select(:psychologist_id, Psychologist.all.collect {|ps| [ps.nombre+" "+ps.apellidoP+" "+ps.apellidoM, ps.id]}, :prompt => 'Selecciona uno')%>
  </div>

  <div class="form-group label-floating">
    <%= f.label "Edades" %> <%= f.label "12 a 14"%> <br>
    <%= f.label :h3,"Hombres" %> <%= f.label :m3,"Mujeres" %><br>
    <%= f.number_field :h3 %> <%= f.number_field :m3 %> <br>
  </div>
       
  <div class="form-group label-floating">
    <%= f.label "Edades" %> <%= f.label "15 a 17"%> <br>
    <%= f.label :h4,"Hombres" %> <%= f.label :m4,"Mujeres" %><br>
    <%= f.number_field :h4 %> <%= f.number_field :m4 %> <br>        
  </div>  

  <div class="actions">
    <%= f.submit "Agregar", class: "btn btn-raised btn-success" %>
  </div>
<% end %>

</div>

app/views/adolescentes_its/edit.html.erb
<div class="row board ">
	<div class="col-md-12">
		<div class="panel panel-success">
		  <div class="panel-heading">
		    <h2 class="panel-title"><i class="fa fa-stethoscope"></i> Editar Datos de Adolescentes que Incian Tratamiento</h2>
		  </div>
		  <div class="panel-body text-center"><h1>Datos del Adolescente Inicia Tratamiento</h1>

        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/adolescentes_its/index.html.erb
<% if notice %>
  <div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= notice %>
  </div>
<% end%>
<div class="row board ">
  <div class="col-md-5">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-search"></i> Buscar Adolescentes IT</h3>
      </div>
      <div class="panel-body text-center">
        <%= form_tag adolescentes_it_path, method: :get do %>
          <div class="form-group label-floating">
            <%= text_field_tag :id_adolescentes_it, params[:id_adolescentes_it] , :class=>"form-control text-center" , placeholder: "ID Adolescentes IT" %>
          </div>
          <div class="actions">
          <%= submit_tag "Buscar", name: nil, class: "btn btn-raised btn-info" %>
          </div>
        <% end %>
        <div class="panel panel-default">
          <div class="list-group">
              <%= render @adolescentes_its %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-7">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h1 class="panel-title"><i class="fa fa-stethoscope"></i> Adolescentes que Inician Tratamiento Agregados</h1>
      </div>
      <div class="panel-body text-center">
        <div class="list-group">
          <%= render @adolescentes_its %>
        </div>
        <%= link_to 'Agregar Adolescentes IT', new_adolescentes_it_path, class: "btn btn-raised btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/adolescentes_its/new.html.erb
<div class="row board ">
	<div class="col-md-12">
		<div class="panel panel-success">
		  <div class="panel-heading">
		    <h2 class="panel-title"><i class="fa fa-stethoscope"></i> Agregar Adolescentes que Inician Tratamiento</h2>
		  </div>
		  <div class="panel-body text-center"><h1>Datos Adolescentes IT</h1>

        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/adolescentes_its/show.html.erb
<div class="row board ">
	<div class="col-md-7">
		<div class="panel panel-success">
		  <div class="panel-heading">
		    <h1 class="panel-title"><i class="fa fa-folder-o"></i> Adolescentes IT <strong>ID <%= @adolescentes_it.id.to_s %></strong></h1>
		  </div>
		  <div class="panel-body text-center">
        <div class="list-group">
          <div class="list-group-item">
            <div class="row-action-primary">
                <i class="fa fa-heartbeat"></i>
            </div>
            <div class="row-content">
              <div class="action-secondary">
                <%= link_to edit_adolescentes_it_path(@adolescentes_it) do %>
                  <i class="fa fa-pencil-square-o"></i>
                <% end %>
              </div>
              <h3 class="list-group-item-heading"><strong>Adolescentes que Inician Tratamiento: <%= @adolescentes_it.id.to_s %></strong></h3>
							<p class="list-group-item-text"><strong>Hombres: </strong><%= @adolescentes_it.h.to_s%></p>
							<p class="list-group-item-text"><strong>Mujeres: </strong><%= @adolescentes_it.m.to_s%></p>
							<p class="list-group-item-text"><strong>Total: </strong><%=(@adolescentes_it.h+@adolescentes_it.m).to_s%></p>
							<p class="list-group-item-text"><strong>Fecha: </strong><%= @adolescentes_it.fecha%><br></p>
							<p class="list-group-item-text"><strong>Psicologo: </strong><%= @adolescentes_it.psychologist_id.to_s%><br></p>
              <p class="list-group-item-text"><strong>Hombres 12 a 14: </strong><%= @adolescentes_it.h3%><br></p>
              <p class="list-group-item-text"><strong>Mujeres 12 a 14: </strong><%= @adolescentes_it.m3.to_s%><br></p>
              <p class="list-group-item-text"><strong>Hombres 15 a 17:</strong><%= @adolescentes_it.h4.to_s%><br></p>
              <p class="list-group-item-text"><strong>Mujeres 15 a 17: </strong><%= @adolescentes_it.m4.to_s%><br></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-5">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-calendar-check-o" aria-hidden="true""></i> Proxima Consulta</h3>
      </div>
      <div class="panel-body">

      </div>
    </div>
  </div>
</div>