config/routes.rb
Rails.application.routes.draw do

  resources :multyproms
  resources :beneficiados
  resources :riesgos
  resources :familiars
    post '/tamizajes' => "apptamizajes#create2", :controller => "apptamizajes"
    post  '/tamizajes/escuela/:id' => "tamizajes#show_tamizaje", as: "show_tamizaje"
    post  '/tamizajes/escuela/grupos/:id' => "tamizajes#show_grupos", as: "show_grupos"
    post  '/tamizajes/escuela/termino_tam/:id' => "tamizajes#termino_tam", as: "termino_tam"
    get  '/tamizajes/escuela/grupos/riesgo/:id' => "tamizajes#show_riesgo", as: "show_riesgo"

  resources :parentescos
  resources :etnia
  resources :civils
    get     "/prueba/:id" => "tamizajes#prueba", as: "prueba"
    post    "/tamizajes/.:id" => "tamizajes#index", as: "escuelas_new_flag"
    get    "/tamizajes/" => "tamizajes#index", as: "escuelas"
    post   "/tamizajes/escuela/tam/new/create" => "tamizajes#create", :controller =>"tamizajes", as: "tam_create"
    post    "/tamizajes/escuela/tam/new"  => "tamizajes#new", as: "new_tamizaje"
    get    "/tamizajes/escuela/:id/edit" => "tamizajes#edit", as: "edit_tamizaje"
    get    "/tamizajes/:id" => "tamizajes#show", as: "tamizaje"
    patch  "/tamizajes/escuela/:id" => "tamizajes#update"
    put    "/tamizajes/escuela/:id" => "tamizajes#update"
    delete "/tamizajes/escuela/:id" => "tamizajes#destroy"

    resources :estatuses
  resources :patients #do
  get '/patients/datos/:id', to: 'patients#datos', as: 'datos'
  get '/meetings/actualizar/:id', to: 'meetings#actualizar', as: 'actualiza'
  resources :imca
  resources :usuarios
  resources :tamizajes_tots
  resources :tratamientos_bcs
  resources :personal_cts
  resources :personas_vgs
  resources :consultas_subs
  resources :consultas_pvs
  resources :capacitaciones_recs
  resources :capacitaciones_ots
  resources :adolescentes_its
  resources :adolescentes_aps
  resources :indicadores
  resources :meta
  resources :psychologists
  resources :expedientes
  resources :sustancia
  resources :programas
  resources :states
  resources :municipios
  resources :meetings
  resources :reportes
  resources :siceca
  resources :indicadoresxedad
  resources :reporte_pacientes
    
  devise_for :users

  resources :user
  get "welcome/index"
  get "meetings/new"

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root "welcome#unregistered", as: :unregistered_root
    end
  end

end

app/models/tamizaje.rb
class Tamizaje < ActiveRecord::Base
    belongs_to :aplicacion_tamizaje
    before_save :default_values
    
    validates :nombre, :presence => {:message => "Nombre no debe ir en blanco." }
    validates :apellidoP, :presence => {:message => "Apellido paterno, no debe ir en blanco." }
    validates :apellidoM, :presence => {:message => "Apellido materno, no debe ir en blanco." }
    validates :sexo, :presence => {:message => "Genero no debe ir en blanco." }
    validates :edad, :presence => {:message => "La edad, no debe ir en blanco." }
    validates :grado, :presence => {:message => "El grado, no debe ir en blanco." }
    validates :grupo, :presence => {:message => "El grupo, no debe ir en blanco." }
    validates :total_uso_sustancias, :presence => {:message => "El total de uso de sustancias fue modificado." }
    validates :total_salud_mental, :presence => {:message => "El total de salud mental fue modificado." }
    validates :total_relacion_familiar, :presence => {:message => "El total de relacion familiar fue modificado." }
    validates :total_relacion_amigos, :presence => {:message => "El total de relacion con amigos fue modificado." }
    validates :total_nivel_educativo, :presence => {:message => "El total de nivel educativo fue modificado." }
    validates :total_interes_laboral,  :presence => {:message => "El total de interes laboral fue modificado." }
    validates :total_conducta_agresiva, :presence => {:message => "El total de conducta agresiva fue modificado." }
    validates :resultado,  presence: {:message => "El resultado fue modificado." }
    validates :aplicacion_tamizaje_id, presence:true
    

    
    def default_values
        if p_usoS.blank?
            self.p_usoS ="0"
        end
        if p_saludM.blank?
            self.p_saludM ="0"
        end
        if p_relacionF.blank?
            self.p_relacionF ="0"
        end
        if p_interesL.blank?
            self.p_interesL ="0"
        end
        if p_relacionA.blank?
            self.p_relacionA ="0"
        end
        if p_nivelE.blank?
            self.p_nivelE ="0"
        end
        if p_conductaA.blank?
            self.p_conductaA ="0"
        end
    end
end

app/controllers/tamizajes_controller.rb
class TamizajesController < ApplicationController
  before_action :set_tamizaje, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authenticate_psicologo!,only: [:index,:create,:edit,:destroy,:update,:show,:new]

  # GET /tamizajes
  # GET /tamizajes.json
  def index
    @escuelas = AplicacionTamizaje.all
    @escuela = AplicacionTamizaje.new
    @escuela.grupos_escuelas.build

    if params[:id] == ""
        redirect_to escuelas_path
        @flag = params[:id]
    else
        @str = params[:id]

        str1 = ""
        if(!@str.nil?)
            str1 = @str["00b1b22cf54d65=1434?"]
        end


        if @str != "00a1b22cf54d65=1434?" && str1 != "00b1b22cf54d65=1434?"
            @flag = "0"
        else
            @flag = "1"
        end


        if str1 == "00b1b22cf54d65=1434?" && @flag == "1"
            @flag += "-2"
        end
        #redirect_to escuelas_path(0)
    end
  end

  # GET /tamizajes/1
  # GET /tamizajes/1.json
  def show
      #@tamizajes = Tamizaje.where("id_escuela = #{params[:id]}")
      @esctemp = AplicacionTamizaje.find(params[:id])
      #redirect_to tamizaje_path(@esctemp)
      respond_to do |format|
        format.html
        format.pdf do
            render pdf:"Informe-#{@esctemp.nivel_estudio.nivel}-#{@esctemp.escuela}-#{@esctemp.municipio}",
          #header: { center: 'hola' },
          #footer: { center: 'hola' },
          layout: 'layouts/pdf.html.erb',
          page_size: 'letter',
          file:'tamizajes/show.pdf.erb'
        end
      end
  end

  def show_tamizaje

      if params[:id] == "new"
          redirect_to new_tamizaje_path
      else
          if request.post?
              id = {
                  :id => params[:'a1b22cf54d65=1435?']
              };
              @tamizaje = Tamizaje.find(id[:id])
          end
          #@otro = Tamizaje.all
      end
  end

  def show_grupos
        if request.post?
            id = {
                :id => params[:'a1c32cf54d65=1434?']
            };
            #@grupos = Tamizaje.find_by_aplicacion_tamizaje_id(id[:id])
            @grupos = Tamizaje.where("aplicacion_tamizaje_id = #{id[:id]}").order(:grado,:grupo,:apellidoP,:apellidoM)
            @esctemp = AplicacionTamizaje.find(id[:id])

            @riesgoMayor = Tamizaje.where("aplicacion_tamizaje_id = #{id[:id]} AND total_uso_sustancias > 3").order(:grado,:grupo,:apellidoP,:apellidoM)

            @riesgoMenor = Tamizaje.where("aplicacion_tamizaje_id = #{id[:id]} AND total_uso_sustancias <= 3 AND total_uso_sustancias > 0").order(:grado,:grupo,:apellidoP,:apellidoM)

        end

          respond_to do |format|
            format.html
            format.pdf do
                render pdf:"Informe-#{@esctemp.nivel_estudio.nivel}-#{@esctemp.escuela}-#{@esctemp.municipio}",
              #header: { center: 'hola' },
              #footer: { center: 'hola' },
              layout: 'layouts/pdf_style_null.html.erb',
              page_size: 'letter',
              file:'tamizajes/show_grupos.pdf.erb',
              orientation: 'Landscape',
              margin:  {   top:10,                     # default 10 (mm)
                            bottom:10,
                            left:10,
                            right:10 }
            end
          end

  end

  def prueba
      @grupos = Tamizaje.where("aplicacion_tamizaje_id = #{params[:id]}").order(:grado,:grupo,:apellidoP,:apellidoM)
      @esctemp = AplicacionTamizaje.find(params[:id])

      @riesgoMayor = Tamizaje.where("aplicacion_tamizaje_id = #{params[:id]} AND total_uso_sustancias > 3").order(:grado,:grupo,:apellidoP,:apellidoM)

            @riesgoMenor = Tamizaje.where("aplicacion_tamizaje_id = #{params[:id]} AND total_uso_sustancias <= 3 AND total_uso_sustancias > 0").order(:grado,:grupo,:apellidoP,:apellidoM)


          respond_to do |format|
            format.html
            format.pdf do
                render pdf:"Informe-#{@esctemp.nivel_estudio.nivel}-#{@esctemp.escuela}-#{@esctemp.municipio}",
              #header: { center: 'hola' },
              #footer: { center: 'hola' },
              layout: 'layouts/pdf_style_null.html.erb',
              page_size: 'letter',
              file:'tamizajes/show_grupos.pdf.erb',
              orientation: 'Landscape',
              margin:  {   top:10,                     # default 10 (mm)
                            bottom:10,
                            left:10,
                            right:10 }

            end
          end

  end


  def show_riesgo
      @esctemp = AplicacionTamizaje.find(params[:id])

      @riesgoMayor = Tamizaje.where("aplicacion_tamizaje_id = #{params[:id]} AND total_uso_sustancias > 3").order(:grado,:grupo,:apellidoP,:apellidoM)

            @riesgoMenor = Tamizaje.where("aplicacion_tamizaje_id = #{params[:id]} AND total_uso_sustancias <= 3 AND total_uso_sustancias > 0").order(:grado,:grupo,:apellidoP,:apellidoM)


          respond_to do |format|
            format.html
            format.pdf do
                render pdf:"Informe-#{@esctemp.nivel_estudio.nivel}-#{@esctemp.escuela}-#{@esctemp.municipio}",
              #header: { center: 'hola' },
              #footer: { center: 'hola' },
              layout: 'layouts/pdf_style_null.html.erb',
              page_size: 'letter',
                file:'tamizajes/show_riesgo.pdf.erb',
              margin:  {   top:10,                     # default 10 (mm)
                            bottom:10,
                            left:10,
                            right:10 }

            end
          end
  end

  def tabla_siceca

  end

  # GET /tamizajes/new
  def new
    @tamizaje = Tamizaje.new
    if request.post?
        id = {
            :id => params[:'a1b22cf54d65=1434?']
        };
        @esctemp = AplicacionTamizaje.find(id[:id])

        x = GruposEscuela.find_by_aplicacion_tamizaje_id(id[:id])
        array = x.grupos.split(",")
        @g_g = {}
        array.each do |a|
            y = a.split("-")
            @g_g [y[0]]=y[1]
        end
    end
  end

  def termino_tam
      if request.post?
          id = {
              :id => params[:'term1b22cf54d65=1434?']
          }
      end
      esc = AplicacionTamizaje.find(id[:id])
      esc.status = "1"
      esc.save
      redirect_to tamizaje_path(esc)

  end

  # GET /tamizajes/1/edit
  def edit
      @tamizaje = Tamizaje.find(params[:id])
  end

  # POST /tamizajes
  # POST /tamizajes.json
  def create
    @tamizaje = Tamizaje.new(tamizaje_params)

    respond_to do |format|
        if request.post?
            @tamizaje.aplicacion_tamizaje_id = params[:"a1b22cf54d65=1434?"]
            @esctemp = AplicacionTamizaje.find(params[:"a1b22cf54d65=1434?"])
            x = GruposEscuela.find_by_aplicacion_tamizaje_id(params[:"a1b22cf54d65=1434?"])
            array = x.grupos.split(",")
            @g_g = {}
            array.each do |a|
                y = a.split("-")
                @g_g [y[0]]=y[1]
            end
            #Tambien @tamizaje[:id_escuela]
        end

        if @tamizaje.save
            format.html { redirect_to tamizaje_path(@tamizaje.aplicacion_tamizaje_id), notice: '¡Tamizaje guardado correctamente!.' }
            #format.html { redirect_to show_tamizaje_url(@tamizaje.id_escuela ,:'a1b22cf54d65=1435?'=>@tamizaje.id),notice: 'Tamizaje was successfully created.' }
        format.json { render :new, status: :created, location: @tamizaje }
      else
            #format.html { redirect_to escuelas_path }
        format.html { render action: 'new' }
        format.json { render json: @tamizaje.errors, status: :unprocessable_entity }
      end
    end
      #:'a1b22cf54d65=1435?'=>@tamizaje.id_escuela),:method => :post
  end

  # PATCH/PUT /tamizajes/1
  # PATCH/PUT /tamizajes/1.json
  def update
    respond_to do |format|
      if @tamizaje.update(tamizaje_params)
        format.html { redirect_to @tamizaje, notice: 'Tamizaje was successfully updated.' }
        format.json { render :show, status: :ok, location: @tamizaje }
      else
        format.html { render :edit }
        format.json { render json: @tamizaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tamizajes/1
  # DELETE /tamizajes/1.json
  def destroy
    @tamizaje.destroy
    respond_to do |format|
      format.html { redirect_to tamizajes_url, notice: 'Tamizaje was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tamizaje
        #@tamizaje = Tamizaje.find(params[:id])
        @tamizajes = Tamizaje.where("aplicacion_tamizaje_id = #{params[:id]}")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tamizaje_params
      params.require(:tamizaje).permit(:nombre, :apellidoP, :apellidoM, :edad, :sexo, :grado, :grupo, :folio_cuestionario, :p_usoS, :total_uso_sustancias, :p_saludM, :total_salud_mental, :p_relacionF, :total_relacion_familiar, :p_relacionA, :total_relacion_amigos, :p_nivelE, :total_nivel_educativo, :p_interesL, :total_interes_laboral, :p_conductaA, :total_conducta_agresiva, :resultado, :aplicacion_tamizaje_id)
    end
end

app/helpers/tamizajes_helper.rb
module TamizajesHelper
end

app/views/tamizajes/_newEsc.html.erb
<div class="col-md-6">
    <div class="panel panel-primary">
       	<div class="panel-heading">
		  <h1 class="panel-title"><i class="fa fa-stethoscope"></i>Datos de la escuela</h1>
        </div>
        
        <%if @flag == "1"%>
            <div class="panel-body text-center">
                  <div class="form-group field">
                      <%no_grupos = {}%>
                      <%for i in (1..15) do%><%no_grupos[i] = i.to_s%><%end%>
                      <div class="row">
                          <%= label_tag :no_grupos,"Numero de grupos:" %>
                            <%= select_tag :no_grupos, options_for_select(no_grupos), class:"select btn-xs",:prompt => '--', id: "no_grupos"%>
                      </div>
                  </div>                
                  <div class="actions">
                      <%= link_to 'Enviar', escuelas_new_flag_path(:'00b1b22cf54d65=1434?'),:method => :post, class:"btn btn-sm btn-primary", id:"btn_no_grupos" %>
                </div>
            </div>
        <%end%>
        
        
        <%if @flag == "1-2"%>
           <%= form_for(@escuela,:controller =>"apptamizajes", url: "/tamizajes", :action => "create2") do |f| %>


              <div class="panel-body text-center">

                  <div class="form-group field">
                      <%= label_tag "Escuela" %>
                      <%= f.text_field :escuela, :class => "form-control text-center"%>
                  </div>
                  <div class="form-group field">
                      <%= label_tag "Colonia " %>
                      <%= f.text_field :colonia, :class => "form-control text-center" %>
                  </div>
                  
                  <div class="form-group field col-md-6">
                      <%= label_tag "Municipio: " %>
                      <%= f.select(:municipio_id, Municipio.all.collect {|mun| [mun.municipio, mun.id]}, :class => "select btn-xs", :prompt => 'Selecciona uno') %>                      
                  </div>
                <div class="form-group field col-md-6">
                    <%= label_tag "Nivel escolar " %>
                    <%= f.select(:nivel_estudio_id,NivelEstudio.all.collect {|estudio| [estudio.nivel, estudio.id]}, :prompt => 'Selecciona uno', :class => "select btn-xs") %>
                </div>
                
                   
                    <%=javascript_tag do%> window.array = [] <%end%>
                    <%grado = {}%>
                    <%for i in (1..15) do%><%grado[i] = i.to_s%><%end%>
                    <%grupo = {:A =>"A",:B =>"B",:C =>"C",:D =>"D",:E =>"E",:F =>"F",:G =>"G",:H =>"H",:I =>"I"}%>
                    <div id="grupos-cont" class="row cont-grupos">
                       <div class="panel-heading">
                           <h5><b>Grupos: </b></h5>                                                              </div>
                    
                    
                    

<% if !@str.nil? %>
    <%no = @str.split("?")%>
    <%num = no[1]%>
    <%for i in (1..num.to_i) do%>
                    <%if (i)%2 == 1 %><div class="row"><%end%>
                  <div class="col-md-5 div-grupo">
                    <div class="form-group field">
                       <div class="panel-heading">
                           <h5><b>Grupo &nbsp;<%= "#{i}:"%></b></h5>                                            </div>
                        
                        
                        <div class="row">
                            <%=label_tag"grado:","Grado:", class: "col-md-3"%>
                            <div class="col-md-3">
                                <%= select_tag "grado", options_for_select(grado), class:"select btn-xs grupo01 ",:prompt => '--', id:"select_gd-#{i-1}" %>
                            </div>

                            <div class="col-md-6">
                                <%=label_tag :"otrogd-#{i-1}", "Otro:"%>
                                <%=check_box_tag :"otrogd-#{i-1}", "",false,class:"check01" %>
                            </div>
                        </div>
                        <div class="row div-txtgd-<%=i-1%>">
                        </div>
                        
                        
                        <div class="row">
                            <%=label_tag"grupo:","Grupo:", class: "col-md-3"%>
                            <div class="col-md-3">
                                <%= select_tag "grupo", options_for_select(grupo), class: "select btn-xs grupo01",:prompt => '--', id:"select_gp-#{i-1}"%>
                            </div>

                            <div class="col-md-6">
                               <%=label_tag :"otrogd-#{i-1}", "Otro: "%>
                                <%=check_box_tag :"otrogp-#{i-1}","",false, class:"check02"%>
                            </div>           
                        </div>
                        <div class="row div-txtgp-<%=i-1%>">
                        </div>
                        
                    </div>
                  </div>
                    <%if (i)%2 == 0 %></div><%end%>
        
        
    <%end%><!--ciclo for-->
<%end%><!--nil?-->
                    </div>
                    
                    
                    
                                                                      
                  <div class="col-md-12">
                    <div class="form-group field">
                        <%= label_tag "Grupos: " %>
                        <%= f.fields_for :grupos_escuelas do |h| %>                        
                            <%= h.text_field :grupos, :class => "form-control text-center", id:"txtf_gs", :readonly => true%>
                        <% end %>
                    </div>
                  </div>                
                 
                  
                
                <div class="actions">
                    <%= link_to "Cancelar", escuelas_path, :class => "btn btn-raised btn-success"%>
                    <%= f.submit "Guardar", :class => "btn btn-raised btn-primary"%>
                </div>
            <%end%><!--end form-->
            </div> <!--body-->
        <%end%><!--end if flag 1-2-->
        
    </div><!--panel-->
        
</div><!--col-md-5-->

app/views/tamizajes/edit.html.erb
<h1>Editing Tamizaje</h1>

<%= render 'form' %>

<%= link_to 'Show', @tamizaje %> |
<%= link_to 'Back', tamizajes_path %>

app/views/tamizajes/index.html.erb
<% if @escuela.errors.any? %>
    <%@flag = "1-2"%>
    <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
        <% @escuela.errors.each do |attribute, message| %>
        <%= message %><br>
    <% end %>
    </div>
<% end %>

<div class="row board">
    <%if  @flag == "1" || @flag == "1-2"%>
        <div class="col-md-6">
        <%x = "f"%>
    <%else%>
        <div class="col-md-12">
        <% x="v"%>
    <%end%>
       <div class="panel">
       	  <div class="panel-heading col-md-12">
       	    <div class="col-md-10">
		        <h3>Escuelas registradas:</h3>
            </div>
            <div class="col-md-2">
                <%= link_to "Nueva Escuela", escuelas_new_flag_path("00a1b22cf54d65=1434?"),:method => :post, class:"btn btn-raised btn-info btn-right-"+x, id: "newesc"%>                
            </div>
		  </div>

          <div class="panel-body text-center position">
             
             <table class="table table-striped table-hover">
              <thead>
                <tr class="text-center">
                  <th class="text-center">#</th>
                  <th class="text-center">Escuela</th>
                  <th class="text-center">Colonia</th>
                  <th class="text-center">Municipio</th>
                  <th class="text-center">Nivel Escolar</th>
                  <th class="text-center">id_Psic</th>
                  <th class="text-center">Status</th>
                  <th></th>
                </tr>
              </thead>

              <tbody>
                <% if (!@escuelas.nil?) %>   
                    <% var = 1;
                        num = 1;%>
                      <% @escuelas.each do |ubicacion| %>
                        <%if (var == 1)%>    
                            <tr class="success">
                            <%var=2%>
                        <%else%>
                            <tr>
                            <%var=1%>
                        <%end%>
                        <td><%= num %></td>  
                        <td><%= ubicacion.escuela %></td>
                        <td><%= ubicacion.colonia %></td>
                        <td><%= ubicacion.municipio.municipio%></td>
                        <td><%= ubicacion.nivel_estudio.nivel %></td>
                        <td><%= ubicacion.psychologist.nombre + " "+ubicacion.psychologist.apellidoP%></td>
                        <%if ubicacion.status == "0"%>
                            <td>Pendiente</td>
                        <%else%>
                            <td>Cerrada</td>
                        <%end%>
                        <td><%= link_to 'Mostrar', tamizaje_path(ubicacion), class:"btn btn-sm btn-primary" %></td>
                      </tr>
                      <%num+=1%>
                    <% end %>
                <% else %>
                    <tr><td colspan="8"><%="No hay escuelas"%></td></tr>
                <%end%>
              </tbody>
            </table>
           
                     
        </div> <!--panel-body-->
        </div><!--panel-info-->
    </div><!--col-mod6-->
    
    <%if  @flag == "1" || @flag == "1-2"%>
       <% if @escuela.errors.any? %>
            <%=render "/tamizajes/newEsc"%>
        <%else%>
            <%=render "newEsc"%>
        <%end%>
    <%end%>

</div><!--row board-->
 


 

app/views/tamizajes/show.html.erb
<div class="row board">
    <div class="col-md-12">
       <div class="panel panel-default">
       	  <div class="panel-heading col-md-12">
       	    <div class="col-md-6">
		        <h3>Escuela:&nbsp;<%=@esctemp.escuela %></h3>
            </div>
            <div class="col-md-2">
              <%= link_to "Filtrar grupos" ,show_grupos_path(:'a1c32cf54d65=1434?' =>@esctemp),:method => :post , class:"btn btn-raised btn-info"%>
            </div>
            
            <%if @esctemp.status == "0"%>
                <div class="col-md-2">
                    <%= link_to "Nuevo Tamizaje", new_tamizaje_path(:'a1b22cf54d65=1434?' =>@esctemp),:method => :post , class:"btn btn-raised btn-success"%>
                </div>
                <div class="col-md-2">
                    <%= link_to "Terminar", termino_tam_path(:'term1b22cf54d65=1434?' =>@esctemp),:method => :post , class:"btn btn-raised btn-warning"%>
                </div>            
            <%end%>
            
		  </div>

          <div class="panel-body text-center position">

             <table class="table table-striped table-hover">
              <thead>
                <tr class="text-center">
                  <th>#</th>
                  <th>Nombre</th>
                  <th>Ap. P.</th>
                  <th>Ap. M.</th>
                  <th>Edad</th>
                  <th>Sexo</th>
                  <th>Grado</th>
                  <th>Grupo</th>
                  <th>Folio</th>
                  <th>Uso sustancias</th>
                  <th>Salud mental</th>
                  <th>Relacion familiar</th>
                  <th>Relacion amigos</th>
                  <th>Nivel educativo</th>
                  <th>Interes laboral</th>
                  <th>Conducta agresiva</th>
                  <th>Resultado</th>
                  <th></th>
                </tr>
              </thead>

              <tbody>
                <% var = 1%>
                <% if (!@tamizajes.nil?) %>
                      <%num = 1%>
                      <% @tamizajes.each do |tamizaje| %>
                          <%if (var == 1)%>
                              <tr class="success">
                              <%var=2%>
                          <%else%>
                              <tr>
                              <%var=1%>
                          <%end%>
                            <td><%=num%></td>
                            <td><%= tamizaje.nombre %></td>
                            <td><%= tamizaje.apellidoP %></td>
                            <td><%= tamizaje.apellidoM %></td>
                            <td><%= tamizaje.edad %></td>
                            <td><%= tamizaje.sexo %></td>
                            <td><%= tamizaje.grado %></td>
                            <td><%= tamizaje.grupo %></td>
                            <td><%= tamizaje.folio_cuestionario %></td>
                            <td>
                                <%if tamizaje.total_uso_sustancias.to_i > 0%>
                                    <b class="riesgo">-
                                <%end%>
                                <%= tamizaje.total_uso_sustancias %>
                                <%if tamizaje.total_uso_sustancias.to_i > 0%>
                                    -</b>
                                <%end%>
                            </td>
                            <td>
                                <%if tamizaje.total_salud_mental.to_i >= 5%>
                                    <b class="riesgo">-
                                <%end%>                                
                                <%= tamizaje.total_salud_mental %>
                                <%if tamizaje.total_salud_mental.to_i >= 5%>
                                    -</b>
                                <%end%>
                            </td>                                
                            <td>
                                <%if tamizaje.total_relacion_familiar.to_i >= 3%>
                                    <b class="riesgo">-
                                <%end%>                                                  
                                <%= tamizaje.total_relacion_familiar %>
                                <%if tamizaje.total_relacion_familiar.to_i >= 3%>
                                    -</b>
                                <%end%>                                
                            </td>
                            <td>
                                <%if tamizaje.total_relacion_amigos.to_i > 0%>
                                    <b class="riesgo">-
                                <%end%>                                                  
                                <%= tamizaje.total_relacion_amigos %>
                                <%if tamizaje.total_relacion_amigos.to_i > 0%>
                                    -</b>
                                <%end%>                               
                            </td>
                            <td>
                                <%if tamizaje.total_nivel_educativo.to_i >= 5%>
                                    <b class="riesgo">-
                                <%end%>                                                  
                                <%= tamizaje.total_nivel_educativo %>
                                <%if tamizaje.total_nivel_educativo.to_i >= 5%>
                                    -</b>
                                <%end%>
                            </td>
                            <td>
                                <%if tamizaje.total_interes_laboral.to_i >= 3%>
                                    <b class="riesgo">-
                                <%end%>                                                  
                                <%= tamizaje.total_interes_laboral %>
                                <%if tamizaje.total_interes_laboral.to_i >= 3%>
                                    -</b>
                                <%end%>
                            </td>
                            <td>
                                <%if tamizaje.total_conducta_agresiva.to_i >=5%>
                                    <b class="riesgo">-
                                <%end%>
                                <%= tamizaje.total_conducta_agresiva %>
                                <%if tamizaje.total_conducta_agresiva.to_i >=5%>
                                    -</b>
                                <%end%>
                            </td>
                            <td>
                                <%if tamizaje.resultado.to_i >= 34%>
                                    <b class="riesgo">-
                                <%end%>
                                <%= tamizaje.resultado %>
                                <%if tamizaje.resultado.to_i >= 34%>
                                    -</b>
                                <%end%>
                            </td>
                            <td><%= link_to 'Mostrar', show_tamizaje_path(:'a1b22cf54d65=1435?' =>tamizaje),:method => :post, class:"btn btn-sm btn-primary" %></td>
                          </tr>
                          <%num+=1%>
                      <% end %>
                <% else %>
                  <tr><td colspan="8"><%="¡No hay tamizajes disponibles!"%></td></tr>
                <%end%>
              </tbody>
            </table>


        </div> <!--panel-body-->
        </div><!--panel-info-->
    </div><!--col-mod12-->

</div><!--row board-->